#!/usr/bin/env python3
import argparse
import json
import re
from pathlib import Path

HEX_RE = re.compile(r"^0x[0-9a-fA-F]+$")
SYMBOL_RE = re.compile(r"^[A-Z][A-Z0-9_]*$")


def sanitize_aliases(aliases):
    if not isinstance(aliases, list):
        return []
    out = []
    for a in aliases:
        if isinstance(a, str) and a.strip():
            out.append(a.strip())
    return out


def parse_int_hex(addr):
    if not isinstance(addr, str) or not HEX_RE.match(addr):
        raise ValueError(f"Invalid address format: {addr}")
    return int(addr, 16)


def sort_records(records):
    return sorted(records, key=lambda r: parse_int_hex(r["address"]))


def load_approved(path):
    doc = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(doc, dict):
        raise ValueError("Top-level JSON must be an object")

    platform = doc.get("platform")
    approved = doc.get("approved")

    if not isinstance(platform, str) or not platform.strip():
        raise ValueError("Missing or invalid platform")
    if not isinstance(approved, list):
        raise ValueError("Missing or invalid approved array")

    filtered = []
    for i, r in enumerate(approved):
        if not isinstance(r, dict):
            raise ValueError(f"approved[{i}] must be an object")

        address = r.get("address")
        symbol = r.get("canonical_linux_symbol")

        if not isinstance(address, str) or not HEX_RE.match(address):
            raise ValueError(f"approved[{i}] has invalid address: {address}")
        if not isinstance(symbol, str) or not SYMBOL_RE.match(symbol):
            raise ValueError(
                f"approved[{i}] has invalid canonical_linux_symbol: {symbol}"
            )

        filtered.append(
            {
                "address": address.lower(),
                "symbol": symbol,
                "platform": r.get("platform", platform),
                "aliases": sanitize_aliases(r.get("apple_aliases", [])),
                "source": r.get("source", {}),
            }
        )

    return platform, sort_records(filtered)


def build_header(platform, records, in_name):
    guard = f"LINUX_MMIO_ALIASES_{platform.upper()}_H"
    lines = []
    lines.append("/* Auto-generated. Do not edit by hand. */")
    lines.append(f"/* Source input: {in_name} */")
    lines.append(f"/* Platform: {platform} */")
    lines.append("")
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append("/*")
    lines.append(" * Linux canonical register names mapped from approved address matches.")
    lines.append(" * This keeps symbols grep-compatible with i915 code and headers.")
    lines.append(" */")
    lines.append("")

    seen_symbol = {}
    seen_addr = {}

    for r in records:
        symbol = r["symbol"]
        addr = r["address"]

        aliases = ", ".join(r["aliases"]) if r["aliases"] else "none"
        src_path = r.get("source", {}).get("path", "")
        src_line = r.get("source", {}).get("line", "")

        note = f"/* addr {addr}; apple aliases: {aliases}"
        if src_path and isinstance(src_line, int):
            note += f"; src {src_path}:{src_line}"
        note += " */"

        if symbol in seen_symbol and seen_symbol[symbol] != addr:
            lines.append(
                f"/* CONFLICT: {symbol} already mapped to {seen_symbol[symbol]}, skipped {addr} */"
            )
            continue
        if addr in seen_addr and seen_addr[addr] != symbol:
            lines.append(
                f"/* CONFLICT: {addr} already mapped to {seen_addr[addr]}, skipped {symbol} */"
            )
            continue

        seen_symbol[symbol] = addr
        seen_addr[addr] = symbol

        lines.append(note)
        lines.append(f"#define {symbol} 0x{int(addr, 16):x}")
        lines.append(f"#define {symbol}__MMIO _MMIO({symbol})")
        lines.append("")

    lines.append(f"#endif /* {guard} */")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate Linux-name-first MMIO header from approved mappings"
    )
    parser.add_argument(
        "input",
        help="Path to approved_auto_renames.json generated by validate_mappings.py",
    )
    parser.add_argument(
        "--out",
        default="linux_mmio_aliases.h",
        help="Output header path",
    )
    args = parser.parse_args()

    in_path = Path(args.input)
    if not in_path.exists():
        raise SystemExit(f"ERROR: input file not found: {in_path}")

    platform, records = load_approved(in_path)
    content = build_header(platform, records, in_path.name)
    Path(args.out).write_text(content, encoding="utf-8")
    print(f"Wrote {args.out} with {len(records)} approved mapping(s)")


if __name__ == "__main__":
    main()
