# Extract AppleIntel framebuffer parameter structs to a C++ header
# @author NootedGreen
# @category AppleIntel
# @keybinding
# @menupath Tools.Apple Intel.Extract Params Header
# @toolbar
# @runtime Jython
#
# What it does:
#   Scans the currently-open Ghidra program (an AppleIntelTGLGraphicsFramebuffer
#   kext disassembly) for the parameter structs we care about (CRTCParams,
#   PLANEPARAMS, SCALERPARAMS, plus anything else added to STRUCT_WHITELIST), and
#   emits AppleIntelParams.hpp with named fields, static_assert offset guards,
#   and `_pad_NNNN` arrays where Ghidra has not yet identified a field.
#
# How to use:
#   1. Open the kext in Ghidra and let auto-analysis finish.
#   2. (Optional) In the Data Type Manager, name each interesting struct
#      (CRTCParams, PLANEPARAMS, SCALERPARAMS) and label fields you've identified.
#      Unnamed slots become _pad_NNNN arrays in the output.
#   3. Drop this file into ~/ghidra_scripts/ (or open Script Manager and add it).
#   4. Run it from Tools → Apple Intel → Extract Params Header. A file picker
#      will ask where to write AppleIntelParams.hpp — point it at your
#      NootedGreen source tree (the existing file will be overwritten).
#
# Also runnable from pyghidra (Python 3 outside Ghidra):
#   pyghidra-run --project-name <name> --project-path <path> extract_apple_params.py
#   In that mode `currentProgram` is provided by pyghidra via the bridge.

from ghidra.program.model.data import Structure, Pointer
import os

# ----------------------------------------------------------------------------
# Configuration
# ----------------------------------------------------------------------------

# Structs to extract. Add new names here as you identify them in Ghidra.
STRUCT_WHITELIST = [
    "CRTCParams",
    "PLANEPARAMS",
    "PlaneParams",        # tolerate casing variants Ghidra may produce
    "SCALERPARAMS",
    "ScalerParams",
    "ppsConfig_t",        # consumed by computePps in setupDSCEngineParams
    "ppsOpt_t",
    "LinkConfig",         # port-side DP link config
]

# Hardcoded references to confirm against Ghidra's discovered offsets. If Ghidra
# disagrees with these on a struct we emit, the script logs a WARNING (this is
# how we catch the case where Ghidra has been edited away from the truth).
EXPECTED_OFFSETS = {
    "CRTCParams": {
        "TRANS_CLK_SEL":       0x00,
        "TRANS_DDI_FUNC_CTL":  0x04,
        "TRANS_DDI_FUNC_CTL2": 0x08,
        "TRANS_MSA_MISC":      0x0C,
        "TRANS_HTOTAL":        0x10,
        "TRANS_HBLANK":        0x14,
        "TRANS_HSYNC":         0x18,
        "TRANS_VTOTAL":        0x1C,
        "TRANS_VBLANK":        0x20,
        "TRANS_VSYNC":         0x24,
        "PIPE_SRCSZ":          0x28,
        "TRANS_CONF":          0x2C,
        "PPS_0":               0x88,
        "PPS_16":              0xB4,
        "DSC_ENGINE_SEL":      0xE8,
        "DSC_JOINER_CTL":      0xEC,
    },
    "SCALERPARAMS": {
        "PS_CTRL":    0x00,
        "PS_WIN_POS": 0x04,
        "PS_WIN_SZ":  0x08,
    },
}

HEADER_PREAMBLE = """//  Copyright \xc2\xa9 2026 Stezza @ inc. Licensed under the Thou Shalt Not Profit License version 1.0.
//  See LICENSE for details.
//
//  AppleIntelParams.hpp \xe2\x80\x94 typed mirror of Apple's framebuffer-driver parameter
//  structures. AUTO-GENERATED by tools/extract_apple_params.py from a Ghidra-
//  analyzed AppleIntelTGLGraphicsFramebuffer.kext. Do not edit by hand \xe2\x80\x94 re-run
//  the script after updating struct definitions in Ghidra.
//
//  Source program: {prog_name}
//  Generated: {timestamp}
//
//  These structs replace raw `pending[N]` uint32_t array indexing in our hooks.
//  Each named field is guarded by a `static_assert` against the offset Ghidra
//  reported when the script ran \xe2\x80\x94 if Ghidra is later edited and a field shifts,
//  the build will fail loudly instead of silently producing wrong code.

#ifndef AppleIntelParams_hpp
#define AppleIntelParams_hpp

#include <stdint.h>

namespace AppleIntel {

"""

HEADER_EPILOGUE = """} // namespace AppleIntel

#endif // AppleIntelParams_hpp
"""

# ----------------------------------------------------------------------------
# Implementation
# ----------------------------------------------------------------------------


def to_field_type(data_type, length):
    """Return a C++ type for a Ghidra DataType + byte length."""
    name = data_type.getName()
    # Common width-based normalizations
    if name in ("undefined4", "dword", "DWORD"):
        return "uint32_t"
    if name in ("undefined2", "word", "WORD", "ushort"):
        return "uint16_t"
    if name in ("undefined1", "byte", "BYTE", "uchar"):
        return "uint8_t"
    if name in ("undefined8", "qword", "QWORD", "ulonglong"):
        return "uint64_t"
    if isinstance(data_type, Pointer):
        inner = data_type.getDataType()
        return "{}*".format(inner.getName() if inner else "void")
    # Fallback: use Ghidra's reported name verbatim
    return name


def sanitize_field_name(raw_name, offset):
    """Return a valid C++ identifier for a field; fall back to field_NNNN."""
    if not raw_name:
        return "field_{:X}".format(offset)
    cleaned = "".join(c if (c.isalnum() or c == "_") else "_" for c in raw_name)
    if cleaned[:1].isdigit():
        cleaned = "_" + cleaned
    return cleaned


def emit_struct(struct):
    """Emit one C++ struct definition + static_asserts."""
    name = struct.getName()
    total = struct.getLength()
    lines = []
    lines.append("// {} \xe2\x80\x94 {} bytes, {} defined components".format(
        name, total, struct.getNumDefinedComponents()))
    lines.append("struct {} {{".format(name))

    written = 0
    asserts = []
    components = list(struct.getDefinedComponents())
    components.sort(key=lambda c: c.getOffset())

    for comp in components:
        offset = comp.getOffset()
        length = comp.getLength()
        dtype = comp.getDataType()
        fname = sanitize_field_name(comp.getFieldName(), offset)

        # Emit padding for any gap before this component
        if offset > written:
            gap = offset - written
            lines.append(
                "    uint8_t _pad_{:X}[0x{:X}]; // +0x{:X}..+0x{:X}".format(
                    written, gap, written, offset - 1))
            written = offset

        ctype = to_field_type(dtype, length)
        # Treat array-typed components as arrays
        if length > 0 and ctype in ("uint32_t", "uint16_t", "uint8_t", "uint64_t"):
            type_size = {"uint64_t": 8, "uint32_t": 4, "uint16_t": 2, "uint8_t": 1}[ctype]
            if length == type_size:
                lines.append("    {:<12} {}; // +0x{:X}".format(ctype, fname, offset))
            else:
                count = length // type_size
                lines.append("    {:<12} {}[{}]; // +0x{:X}".format(
                    ctype, fname, count, offset))
        else:
            lines.append("    {:<12} {}; // +0x{:X}, len 0x{:X}".format(
                ctype, fname, offset, length))

        # Skip pad-style autogenerated names
        if not fname.startswith("field_") and not fname.startswith("_pad_"):
            asserts.append(
                "static_assert(__builtin_offsetof({}, {}) == 0x{:X}, \"{}.{} offset\");".format(
                    name, fname, offset, name, fname))
        written = offset + length

    # Trailing pad to struct size
    if written < total:
        gap = total - written
        lines.append(
            "    uint8_t _pad_{:X}[0x{:X}]; // +0x{:X}..+0x{:X} (trailing)".format(
                written, gap, written, total - 1))

    lines.append("};")
    lines.append("static_assert(sizeof({}) == 0x{:X}, \"{} total size\");".format(
        name, total, name))
    lines.extend(asserts)

    # Cross-check expected offsets, warn on mismatch
    if name in EXPECTED_OFFSETS:
        actual = {sanitize_field_name(c.getFieldName(), c.getOffset()): c.getOffset()
                  for c in components if c.getFieldName()}
        for fname, exp_off in EXPECTED_OFFSETS[name].items():
            if fname in actual and actual[fname] != exp_off:
                print("WARNING: {}.{} is at 0x{:X}, expected 0x{:X}".format(
                    name, fname, actual[fname], exp_off))

    lines.append("")
    return "\n".join(lines)


def find_struct(dtm, name):
    """Locate a Structure by name in Ghidra's DataTypeManager."""
    for st in dtm.getAllStructures():
        if st.getName() == name:
            return st
    return None


def main():
    program = currentProgram
    if program is None:
        print("No program open in Ghidra")
        return

    dtm = program.getDataTypeManager()
    found = []
    for wanted in STRUCT_WHITELIST:
        st = find_struct(dtm, wanted)
        if st is None:
            print("INFO: struct '{}' not found in {}; skipping".format(
                wanted, program.getName()))
            continue
        found.append(st)

    if not found:
        print("No whitelisted structs found. Define them in Ghidra first or extend STRUCT_WHITELIST.")
        return

    out_path = askFile("Save AppleIntelParams.hpp to", "Save")
    out_file = out_path.getAbsolutePath()

    import datetime
    body = HEADER_PREAMBLE.format(
        prog_name=program.getName(),
        timestamp=datetime.datetime.now().isoformat(),
    )
    for st in found:
        body += emit_struct(st) + "\n"
    body += HEADER_EPILOGUE

    with open(out_file, "w") as f:
        f.write(body)

    print("Wrote {} structs to {}".format(len(found), out_file))


main()
