name: Build NootedGreen
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: xcodebuild -project NootedGreen.xcodeproj -scheme NootedGreen -configuration Release CONFIGURATION_BUILD_DIR=$(pwd)/build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: NootedGreen-Release
          path: build/*.kext
